In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
orders = pd.read_csv('data/orders.csv')
order_products_prior = pd.read_csv('data/order_products__prior.csv')
products = pd.read_csv('data/products.csv')
aisles = pd.read_csv('data/aisles.csv')
departments = pd.read_csv('data/departments.csv')

In [16]:
(orders.days_since_prior_order.isnull().sum()/len(orders.days_since_prior_order))*100

6.027594185817766

In [22]:
orders['days_since_prior_order'] = orders.groupby('user_id')['days_since_prior_order'].transform(
    lambda x: x.fillna(x.median()))

In [24]:
orders.iloc[:50]

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,19.5
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0
11,2168274,2,prior,1,2,11,13.0
12,1501582,2,prior,2,5,10,10.0
13,1901567,2,prior,3,1,10,3.0
14,738281,2,prior,4,2,10,8.0
15,1673511,2,prior,5,3,11,8.0
16,1199898,2,prior,6,2,9,13.0
17,3194192,2,prior,7,2,12,14.0
18,788338,2,prior,8,1,15,27.0
19,1718559,2,prior,9,2,9,8.0
20,1447487,2,prior,10,1,11,6.0
21,1402090,2,prior,11,1,10,30.0
22,3186735,2,prior,12,1,9,28.0
23,3268552,2,prior,13,4,11,30.0
24,839880,2,prior,14,3,10,13.0
25,1492625,2,train,15,1,11,30.0
26,1374495,3,prior,1,1,14,11.0
27,444309,3,prior,2,3,19,9.0
28,3002854,3,prior,3,3,16,21.0
29,2037211,3,prior,4,2,18,20.0
30,2710558,3,prior,5,0,17,12.0
31,1972919,3,prior,6,0,16,7.0
32,1839752,3,prior,7,0,15,7.0
33,3225766,3,prior,8,0,17,7.0
34,3160850,3,prior,9,0,16,7.0
35,676467,3,prior,10,3,16,17.0
36,521107,3,prior,11,0,18,11.0
37,1402502,3,prior,12,1,15,15.0
38,2774568,3,test,13,5,15,11.0
39,3343014,4,prior,1,6,11,19.0
40,2030307,4,prior,2,4,11,19.0
41,691089,4,prior,3,4,15,21.0
42,94891,4,prior,4,5,13,15.0
43,2557754,4,prior,5,5,13,0.0
44,329954,4,test,6,3,12,30.0
45,2717275,5,prior,1,3,12,10.5
46,1909121,5,prior,2,0,16,11.0
47,2267326,5,prior,3,3,18,10.0
48,157374,5,prior,4,1,18,19.0
49,2196797,5,train,5,0,11,6.0

In [27]:
total_order = orders.groupby('user_id')['order_number'].max()
total_order

user_id
1         11
2         15
3         13
4          6
5          5
          ..
206205     4
206206    68
206207    17
206208    50
206209    14
Name: order_number, Length: 206209, dtype: int64

In [29]:
orders

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0